server:
  port: 8080
  servlet:
    context-path: /api

spring:
  application:
    name: api-gateway
  profiles:
    active: default
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]': #对所有路径增加CORS配置
            allowedOrigins: '*' #支持跨域
            allowedMethods: GET,POST,PUT,DELETE,OPTIONS
      routes:
        #系统管理服务
        - id: system-service
          uri: lb://system-service #使用负载均衡模式
          predicates:
            - Path=/**

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://${EUREKA_URL}/eureka

anonymous-uris: #自定义匿名访问地址，可以通过正则表达式进行匹配
  /auth/**,
  /sms/send