server:
  port: 8081
  servlet:
    context-path: /

spring:
  application:
    name: system-service
  profiles:
    active: default
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false
  #Redis连接参数
  redis:
    host: ${REDIS_HOST}
    port: ${REDIS_PORT}
    password: ${REDIS_PASSWD}
    database: 1

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://${EUREKA_URL}/eureka

swagger2:
  enabled: true
  base-package: com.example
  api-info:
    title: Example
    name: Example
    url: http://example.org
    email:
    version: 1.0